-- Tüm Türkiye'deki üniversitelerin listesi
INSERT INTO universiteler (ad) VALUES ('ABANT İZZET BAYSAL ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('ABDULLAH GÜL ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('ACIBADEM ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('ADANA BİLİM VE TEKNOLOJİ ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('ADIYAMAN ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('ADNAN MENDERES ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('AFYON KOCATEPE ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('AĞRI İBRAHİM ÇEÇEN ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('AHİ EVRAN ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('AKDENİZ ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('AKSARAY ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('ALANYA HAMDULLAH EMİN PAŞA ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('AMASYA ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('ANADOLU ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('ANKARA BİLGE ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('ANKARA ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('ARDAHAN ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('ARTVİN ÇORUH ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('ATATÜRK ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('ATILIM ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('AVRASYA ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('BAHÇEŞEHİR ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('BALIKESİR ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('BANDIRMA ONYEDİ EYLÜL ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('BARTIN ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('BAŞKENT ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('BAYBURT ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('BEYKENT ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('BEYKOZ ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('BEZM-İ ÂLEM VAKIF ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('BİLECİK ŞEYH EDEBALİ ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('BİNGÖL ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('BİRUNİ ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('BİTLİS EREN ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('BOĞAZİÇİ ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('BOLU ABANT İZZET BAYSAL ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('BURDUR MEHMET AKİF ERSOY ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('BURSA TEKNİK ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('BURSA ULUDAĞ ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('ÇAĞ ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('ÇANAKKALE ONSEKİZ MART ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('ÇANKAYA ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('ÇANKIRI KARATEKİN ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('ÇUKUROVA ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('DİCLE ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('DOĞUŞ ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('DOKUZ EYLÜL ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('DÜZCE ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('EGE ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('ERCİYES ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('ERZİNCAN BİNALİ YILDIRIM ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('ERZURUM TEKNİK ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('ESKİŞEHİR OSMANGAZİ ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('ESKİŞEHİR TEKNİK ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('FATİH SULTAN MEHMET VAKIF ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('FATİH ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('FIRAT ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('GALATASARAY ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('GAZİ ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('GAZİANTEP ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('GEBZE TEKNİK ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('GİRESUN ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('GÜMÜŞHANE ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('HACETTEPE ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('HAKKARİ ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('HALİÇ ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('HARRAN ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('HASAN KALYONCU ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('HATAY MUSTAFA KEMAL ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('HİTİT ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('IĞDIR ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('İBN HALDUN ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('İHSAN DOĞRAMACI BİLKENT ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('İNÖNÜ ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('İSKENDERUN TEKNİK ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('İSTANBUL AYDIN ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('İSTANBUL BİLGİ ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('İSTANBUL GEDİK ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('İSTANBUL KENT ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('İSTANBUL MEDENİYET ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('İSTANBUL MEDİPOL ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('İSTANBUL SABAHATTİN ZAİM ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('İSTANBUL TEKNİK ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('İSTANBUL TİCARET ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('İSTANBUL ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('İSTANBUL ÜNİVERSİTESİ-CERRAHPAŞA');
INSERT INTO universiteler (ad) VALUES ('İSTİNYE ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('İZMİR BAKIRÇAY ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('İZMİR DEMOKRASİ ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('İZMİR EKONOMİ ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('İZMİR KATİP ÇELEBİ ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('İZMİR YÜKSEK TEKNOLOJİ ENSTİTÜSÜ');
INSERT INTO universiteler (ad) VALUES ('KADİR HAS ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('KAFKAS ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('KAHRAMANMARAŞ SÜTÇÜ İMAM ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('KAPADOKYA ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('KARABÜK ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('KARADENİZ TEKNİK ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('KARAMANOĞLU MEHMETBEY ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('KASTAMONU ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('KOÇ ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('KONYA TEKNİK ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('KONYA ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('KTO KARATAY ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('MALATYA TURGUT ÖZAL ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('MANİSA CELÂL BAYAR ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('MARDİN ARTUKLU ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('MARMARA ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('MEF ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('MERSİN ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('MİMAR SİNAN GÜZEL SANATLAR ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('MUĞLA SITKI KOÇMAN ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('MUNZUR ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('NECMETTİN ERBAKAN ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('NEVŞEHİR HACI BEKTAŞ VELİ ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('NİĞDE ÖMER HALİSDEMİR ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('NİŞANTAŞI ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('NUH NACİ YAZGAN ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('ONDOKUZ MAYIS ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('ORDU ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('ORTA DOĞU TEKNİK ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('OSMANİYE KORKUT ATA ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('ÖZYEĞİN ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('PAMUKKALE ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('PİRİ REİS ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('RECEP TAYYİP ERDOĞAN ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('SAKARYA ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('SAMSUN ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('SELÇUK ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('SİİRT ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('SİNOP ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('SİVAS BİLİM VE TEKNOLOJİ ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('SİVAS CUMHURİYET ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('ŞIRNAK ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('TARSUS ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('TED ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('TOBB EKONOMİ VE TEKNOLOJİ ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('TOKAT GAZİOSMANPAŞA ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('TRABZON ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('TRAKYA ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('TÜRK-ALMAN ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('TÜRK HAVA KURUMU ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('UFUK ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('UŞAK ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('YALOVA ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('YAŞAR ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('YEDİTEPE ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('YILDIRIM BEYAZIT ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('YILDIZ TEKNİK ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('YOZGAT BOZOK ÜNİVERSİTESİ');
INSERT INTO universiteler (ad) VALUES ('ZONGULDAK BÜLENT ECEVİT ÜNİVERSİTESİ'); 